### ISSUE TITLE
rework README

### ISSUE THREAD

**Issue by Daniel-Valentine** [libreddit/ferrit#2]
The README will need to be rewritten.

1. With the name change, references to the previous "libreddit" will need to be changed to the new name of the project (currently "libbacon"). See libbacon/libbacon#3.
1. Libreddit instances will need to be removed. At the time of writing this issue, there are no running instances of libbacon.
1. @spikecodes' donation options and crypto addresses need to be removed. libbacon is based on @spikecodes' excellent work, but this is a fork that they do not (presently) manage. **I have no plans to solicit donations for this project.**
1. There are also items in the original README that are or may be out-of-date. I will have to redo Google Lighthouse speed-tests of libbacon and teddit (and perhaps we can do a comparison against Python-based [kddit](https://gt.kalli.st/kallist/kddit-spaghetti)). I will also review the summary of Reddit's privacy policy to see if it needs an update.
1. I will probably remove the links to the replit/heroku/glitch deployment options until this fork is mature enough, i.e. at least libbacon/libbacon#3 is addressed.
1. We need a new screenshot, or screenshots.

**Comment by shruuub** [comment]
I could do some of the work, mainly a quick spin up tutorial for docker, speedtests and screenshots.

**Comment by Daniel-Valentine** [comment]
Closed with the resumption of the Libreddit project.
