### ISSUE TITLE
💡 Feature request: Libreddit backwards compatibility

### ISSUE THREAD

**Issue by Midou36O** [libreddit/ferrit#50]
## Is your feature request related to a problem? Please describe.

Ferrit does not currently supports libreddit environment variables as mentionned in the [Wiki](https://github.com/ferritreader/ferrit/wiki/FAQ#i-host-a-libreddit-instance-can-i-use-ferrit-as-a-drop-in-replacement)

## Describe the feature you would like to be implemented
Add a backwards compatibility feature where the  libreddit environment variables are supported by ferrit to be able to replace libreddit without too much hassle.

## Describe alternatives you've considered
Renaming, but that's a bit annoying to do. Maybe document a way to convert libreddit keywords with ferrit using `sed` if possible.

## Additional context / screenshot
n/a

**Comment by Daniel-Valentine** [comment]
I'm planning a rework of how Ferrit manages config settings in the backend. I think as part of that I can tackle this as well.

**Comment by Midou36O** [comment]
> I'm planning a rework of how Ferrit manages config settings in the backend. I think as part of that I can tackle this as well.

Using toml config? Json?

**Comment by Daniel-Valentine** [comment]
Closed with the resumption of the Libreddit project (though if Libreddit changes its name we'll have to keep this in mind).
